name: Update Catalog

on:
  schedule:
    # Roda diariamente à meia-noite UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Permite rodar manualmente via aba "Actions"

permissions:
  contents: write

jobs:
  update-catalog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.2

    - name: Set up Go
      uses: actions/setup-go@v6.2.0
      with:
        go-version: '1.25.6'

    - name: Run Generator
      env:
        # Necessário para a estratégia "github_release" não tomar Rate Limit
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Executa a partir do novo entrypoint definido na arquitetura
      run: go run cmd/generator/main.go

    - name: Commit and Push if changed
      run: |
        git config --global user.name 'Updater-Registry-Bot'
        git config --global user.email 'updater-registry-bot@users.noreply.github.com'
        
        # Adiciona tanto o catálogo unificado quanto os arquivos individuais
        git add api/catalog.json packages/
        
        # Só commita se houver algo no stage
        git diff --staged --quiet || (git commit -m "Update catalog and packages [skip ci]" && git push)